# Generated by Django 3.1.7 on 2021-03-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodjango', '0002_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='picture',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
